### ISSUE TITLE
Unable to log in

### ISSUE THREAD

**Issue by Kazz3r24** [musicmancorley/TheBriarPatch#4]
I just finished installing BriarIDS onto my Raspberry Pi 2, as well as TheBriarPatch. Everything installed successfully, only issue is when I try to sign in with the default username and password, or even create a new user and try to log in with it, I get looped back to the login screen.

Any assistance would be appreciated!

Thank you,

**Comment by musicmancorley** [comment]
Hey there @Kazz3r24 
Would you please copy and paste the contents of /var/log/apache2/error.log into this issue request?
that should give me an idea as to what is preventing you from going beyond the login screen, etc
thanks
-Robbie

**Comment by Kazz3r24** [comment]
Hey Robbie,

As requested before is the contents of my /var/log/apache2/error.log. Please let me know if there is anything further I can provide for you. I assume the issue is something small that I've missed during configuration, though I did follow the guide.

Thanks for the assist!

cat /var/log/apache2/error.log 
[Tue Jun 06 04:14:11.320035 2017] [mpm_event:notice] [pid 25805:tid 1995759616] AH00489: Apache/2.4.10 (Raspbian) configured -- resuming normal operations
[Tue Jun 06 04:14:11.320964 2017] [core:notice] [pid 25805:tid 1995759616] AH00094: Command line: '/usr/sbin/apache2'
[Tue Jun 06 04:19:05.309879 2017] [mpm_event:notice] [pid 25805:tid 1995759616] AH00491: caught SIGTERM, shutting down
[Tue Jun 06 04:19:07.614942 2017] [ssl:warn] [pid 26286:tid 1995476992] AH01906: 127.0.1.1:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Tue Jun 06 04:19:07.615375 2017] [ssl:warn] [pid 26286:tid 1995476992] AH01909: 127.0.1.1:443:0 server certificate does NOT include an ID which matches the server name
[Tue Jun 06 04:19:07.691495 2017] [ssl:warn] [pid 26287:tid 1995476992] AH01906: 127.0.1.1:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Tue Jun 06 04:19:07.691690 2017] [ssl:warn] [pid 26287:tid 1995476992] AH01909: 127.0.1.1:443:0 server certificate does NOT include an ID which matches the server name
[Tue Jun 06 04:19:07.697047 2017] [mpm_event:notice] [pid 26287:tid 1995476992] AH00489: Apache/2.4.10 (Raspbian) OpenSSL/1.0.1t configured -- resuming normal operations
[Tue Jun 06 04:19:07.697339 2017] [core:notice] [pid 26287:tid 1995476992] AH00094: Command line: '/usr/sbin/apache2'
[Tue Jun 06 04:23:57.178591 2017] [mpm_event:notice] [pid 26287:tid 1995476992] AH00491: caught SIGTERM, shutting down
[Tue Jun 06 04:24:00.121387 2017] [ssl:warn] [pid 26518:tid 1996341248] AH01906: 127.0.0.1:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Tue Jun 06 04:24:00.121821 2017] [ssl:warn] [pid 26518:tid 1996341248] AH01909: 127.0.0.1:443:0 server certificate does NOT include an ID which matches the server name
[Tue Jun 06 04:24:00.196584 2017] [ssl:warn] [pid 26519:tid 1996341248] AH01906: 127.0.0.1:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Tue Jun 06 04:24:00.196801 2017] [ssl:warn] [pid 26519:tid 1996341248] AH01909: 127.0.0.1:443:0 server certificate does NOT include an ID which matches the server name
[Tue Jun 06 04:24:00.202268 2017] [mpm_event:notice] [pid 26519:tid 1996341248] AH00489: Apache/2.4.10 (Raspbian) OpenSSL/1.0.1t configured -- resuming normal operations
[Tue Jun 06 04:24:00.202506 2017] [core:notice] [pid 26519:tid 1996341248] AH00094: Command line: '/usr/sbin/apache2'
[Tue Jun 06 04:25:38.782833 2017] [mpm_event:notice] [pid 26519:tid 1996341248] AH00491: caught SIGTERM, shutting down
[Tue Jun 06 04:25:40.863360 2017] [ssl:warn] [pid 26659:tid 1995517952] AH01906: 127.0.0.1:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Tue Jun 06 04:25:40.863783 2017] [ssl:warn] [pid 26659:tid 1995517952] AH01909: 127.0.0.1:443:0 server certificate does NOT include an ID which matches the server name
[Tue Jun 06 04:25:40.939277 2017] [ssl:warn] [pid 26660:tid 1995517952] AH01906: 127.0.0.1:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Tue Jun 06 04:25:40.939505 2017] [ssl:warn] [pid 26660:tid 1995517952] AH01909: 127.0.0.1:443:0 server certificate does NOT include an ID which matches the server name
[Tue Jun 06 04:25:40.946356 2017] [mpm_event:notice] [pid 26660:tid 1995517952] AH00489: Apache/2.4.10 (Raspbian) OpenSSL/1.0.1t configured -- resuming normal operations
[Tue Jun 06 04:25:40.946664 2017] [core:notice] [pid 26660:tid 1995517952] AH00094: Command line: '/usr/sbin/apache2'
[Tue Jun 06 04:32:44.831657 2017] [mpm_event:notice] [pid 26660:tid 1995517952] AH00491: caught SIGTERM, shutting down
[Tue Jun 06 04:32:47.762215 2017] [ssl:warn] [pid 30954] AH01906: 127.0.0.1:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Tue Jun 06 04:32:47.762668 2017] [ssl:warn] [pid 30954] AH01909: 127.0.0.1:443:0 server certificate does NOT include an ID which matches the server name
[Tue Jun 06 04:32:47.841250 2017] [ssl:warn] [pid 30955] AH01906: 127.0.0.1:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Tue Jun 06 04:32:47.841543 2017] [ssl:warn] [pid 30955] AH01909: 127.0.0.1:443:0 server certificate does NOT include an ID which matches the server name
[Tue Jun 06 04:32:47.853057 2017] [mpm_prefork:notice] [pid 30955] AH00163: Apache/2.4.10 (Raspbian) OpenSSL/1.0.1t configured -- resuming normal operations
[Tue Jun 06 04:32:47.853330 2017] [core:notice] [pid 30955] AH00094: Command line: '/usr/sbin/apache2'
[Tue Jun 06 04:33:24.337498 2017] [mpm_prefork:notice] [pid 30955] AH00169: caught SIGTERM, shutting down
[Tue Jun 06 04:33:26.990654 2017] [ssl:warn] [pid 31059] AH01906: 127.0.0.1:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Tue Jun 06 04:33:31.768542 2017] [ssl:warn] [pid 31059] AH01909: 127.0.0.1:443:0 server certificate does NOT include an ID which matches the server name
[Tue Jun 06 04:33:33.797099 2017] [ssl:warn] [pid 31060] AH01906: 127.0.0.1:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Tue Jun 06 04:33:33.797340 2017] [ssl:warn] [pid 31060] AH01909: 127.0.0.1:443:0 server certificate does NOT include an ID which matches the server name
[Tue Jun 06 04:33:33.812829 2017] [mpm_prefork:notice] [pid 31060] AH00163: Apache/2.4.10 (Raspbian) OpenSSL/1.0.1t configured -- resuming normal operations
[Tue Jun 06 04:33:33.813075 2017] [core:notice] [pid 31060] AH00094: Command line: '/usr/sbin/apache2'
[Tue Jun 06 04:34:50.686079 2017] [mpm_prefork:notice] [pid 31060] AH00169: caught SIGTERM, shutting down
[Tue Jun 06 04:34:59.598188 2017] [ssl:warn] [pid 31331] AH01906: 127.0.0.1:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Tue Jun 06 04:34:59.598594 2017] [ssl:warn] [pid 31331] AH01909: 127.0.0.1:443:0 server certificate does NOT include an ID which matches the server name
[Tue Jun 06 04:34:59.823706 2017] [ssl:warn] [pid 31332] AH01906: 127.0.0.1:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Tue Jun 06 04:34:59.823913 2017] [ssl:warn] [pid 31332] AH01909: 127.0.0.1:443:0 server certificate does NOT include an ID which matches the server name
[Tue Jun 06 04:34:59.839784 2017] [mpm_prefork:notice] [pid 31332] AH00163: Apache/2.4.10 (Raspbian) OpenSSL/1.0.1t configured -- resuming normal operations
[Tue Jun 06 04:34:59.840037 2017] [core:notice] [pid 31332] AH00094: Command line: '/usr/sbin/apache2'
[Tue Jun 06 04:35:11.206469 2017] [:error] [pid 31336] [client 192.168.0.211:53742] PHP Warning:  fwrite() expects at least 2 parameters, 1 given in /var/www/html/TheBriarPatch/Login.php on line 46
[Tue Jun 06 04:35:11.206775 2017] [:error] [pid 31336] [client 192.168.0.211:53742] PHP Fatal error:  Class 'SQLite3' not found in /var/www/html/TheBriarPatch/Login.php on line 53
[Tue Jun 06 04:35:34.147018 2017] [:error] [pid 31348] [client 192.168.0.211:53748] PHP Fatal error:  Class 'SQLite3' not found in /var/www/html/TheBriarPatch/Login.php on line 53, referer: https://192.168.0.148/TheBriarPatch/Login.php
[Tue Jun 06 04:35:55.211318 2017] [:error] [pid 31348] [client 192.168.0.211:53753] PHP Fatal error:  Class 'SQLite3' not found in /var/www/html/TheBriarPatch/Login.php on line 53, referer: https://192.168.0.148/TheBriarPatch/Login.php
[Tue Jun 06 04:36:25.872941 2017] [:error] [pid 31339] [client 192.168.0.211:53762] PHP Fatal error:  Class 'SQLite3' not found in /var/www/html/TheBriarPatch/Login.php on line 53, referer: https://192.168.0.148/TheBriarPatch/CreateUser.php
[Tue Jun 06 04:36:33.513059 2017] [:error] [pid 31335] [client 192.168.0.211:53767] PHP Fatal error:  Class 'SQLite3' not found in /var/www/html/TheBriarPatch/Login.php on line 53, referer: https://192.168.0.148/TheBriarPatch/Login.php
[Tue Jun 06 04:36:45.779155 2017] [:error] [pid 31338] [client 192.168.0.211:53775] PHP Fatal error:  Class 'SQLite3' not found in /var/www/html/TheBriarPatch/Login.php on line 53, referer: https://192.168.0.148/TheBriarPatch/Login.php
[Tue Jun 06 04:37:05.367193 2017] [:error] [pid 31348] [client 192.168.0.211:53780] PHP Fatal error:  Class 'SQLite3' not found in /var/www/html/TheBriarPatch/Login.php on line 53, referer: https://192.168.0.148/
[Tue Jun 06 04:37:18.180027 2017] [:error] [pid 31339] [client 192.168.0.211:53785] PHP Fatal error:  Class 'SQLite3' not found in /var/www/html/TheBriarPatch/Login.php on line 53, referer: https://192.168.0.148/TheBriarPatch/Login.php
[Tue Jun 06 05:59:01.748772 2017] [mpm_prefork:notice] [pid 31332] AH00169: caught SIGTERM, shutting down
[Tue Jun 06 05:17:10.413093 2017] [ssl:warn] [pid 596] AH01906: 127.0.0.1:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Tue Jun 06 05:17:10.422381 2017] [ssl:warn] [pid 596] AH01909: 127.0.0.1:443:0 server certificate does NOT include an ID which matches the server name
[Tue Jun 06 05:17:11.240896 2017] [ssl:warn] [pid 597] AH01906: 127.0.0.1:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Tue Jun 06 05:17:11.241109 2017] [ssl:warn] [pid 597] AH01909: 127.0.0.1:443:0 server certificate does NOT include an ID which matches the server name
[Tue Jun 06 05:17:11.255980 2017] [mpm_prefork:notice] [pid 597] AH00163: Apache/2.4.10 (Raspbian) OpenSSL/1.0.1t configured -- resuming normal operations
[Tue Jun 06 05:17:11.256221 2017] [core:notice] [pid 597] AH00094: Command line: '/usr/sbin/apache2'

**Comment by Kazz3r24** [comment]
I believe I already see the issue. SQLite3 not installed. I will configure this and report back if that resolves the issue.

**Comment by Kazz3r24** [comment]
I can confirm the issue has been resolved.
Installed php5-sqlite and sendmail, everything looks fine now.
Thank you for getting my to look at the log, should have done that sooner!

**Comment by musicmancorley** [comment]
Glad to hear it cooperated for you!
